-- =============================================================================
-- SynapseCortex AI | Patient 360 & Clinical Regulatory Copilot
-- Script  : 04_stage_and_load.sql
-- Purpose : PUT unstructured clinical text files into @RAW.CLINICAL_STAGE,
--           then COPY structured CSVs into the four RAW core tables.
-- Author  : SynapseCortex Data Engineering
-- Date    : 2026-09-13
-- =============================================================================
-- PREREQUISITES:
--   1. Run 01_database_schemas.sql
--   2. Run 02_raw_tables.sql
--   3. Run 03_clinical_stage.sql
--   4. Run data_generator/generate_synthetic_data.py → creates output/*.csv
--   5. Update LOCAL_BASE_PATH below to match your machine's absolute path
--      before executing the PUT commands.
-- =============================================================================

USE DATABASE SYNAPSE_HEALTH;
USE SCHEMA RAW;

-- ─────────────────────────────────────────────────────────────────────────────
-- STEP 1 – PUT CLINICAL NOTES into @RAW.CLINICAL_STAGE/clinical_notes/
-- ─────────────────────────────────────────────────────────────────────────────
-- Execute these PUT commands from a SnowSQL session or Snowflake worksheet.
-- Replace <LOCAL_BASE_PATH> with the absolute path on your local machine.
--
-- Example (Windows):
--   SET LOCAL_BASE_PATH = 'C:/Users/Asus/OneDrive/Desktop/SynapseCortex AI Patient & Member 360 & Clinical Regulatory Copilot/clinical_docs';

-- Hero 1 – Robert Callahan (Safety Violation)
PUT file://<LOCAL_BASE_PATH>/clinical_notes/hero1_note_ROBERT_CALLAHAN.txt
    @RAW.CLINICAL_STAGE/clinical_notes/
    AUTO_COMPRESS = FALSE
    OVERWRITE     = TRUE;

-- Hero 2 – Linda Moreno (Care Gap)
PUT file://<LOCAL_BASE_PATH>/clinical_notes/hero2_note_LINDA_MORENO.txt
    @RAW.CLINICAL_STAGE/clinical_notes/
    AUTO_COMPRESS = FALSE
    OVERWRITE     = TRUE;

-- Hero 3 – James Whitfield (High Risk) – 3 notes
PUT file://<LOCAL_BASE_PATH>/clinical_notes/hero3_note_JAMES_WHITFIELD_inpatient.txt
    @RAW.CLINICAL_STAGE/clinical_notes/
    AUTO_COMPRESS = FALSE
    OVERWRITE     = TRUE;

PUT file://<LOCAL_BASE_PATH>/clinical_notes/hero3_note_JAMES_WHITFIELD_outpatient.txt
    @RAW.CLINICAL_STAGE/clinical_notes/
    AUTO_COMPRESS = FALSE
    OVERWRITE     = TRUE;

PUT file://<LOCAL_BASE_PATH>/clinical_notes/hero3_note_JAMES_WHITFIELD_ED.txt
    @RAW.CLINICAL_STAGE/clinical_notes/
    AUTO_COMPRESS = FALSE
    OVERWRITE     = TRUE;

-- ─────────────────────────────────────────────────────────────────────────────
-- STEP 2 – PUT FDA PACKAGE INSERT TEXT into @RAW.CLINICAL_STAGE/fda_inserts/
-- ─────────────────────────────────────────────────────────────────────────────

-- Hero 1 – Metformin contraindication in CKD
PUT file://<LOCAL_BASE_PATH>/fda_inserts/fda_insert_METFORMIN.txt
    @RAW.CLINICAL_STAGE/fda_inserts/
    AUTO_COMPRESS = FALSE
    OVERWRITE     = TRUE;

-- Hero 2 – HbA1c monitoring standard (HEDIS / ADA)
PUT file://<LOCAL_BASE_PATH>/fda_inserts/fda_insert_HBA1C_MONITORING_STANDARD.txt
    @RAW.CLINICAL_STAGE/fda_inserts/
    AUTO_COMPRESS = FALSE
    OVERWRITE     = TRUE;

-- Hero 3 – Polypharmacy high-risk profile
PUT file://<LOCAL_BASE_PATH>/fda_inserts/fda_insert_POLYPHARMACY_HIGH_RISK.txt
    @RAW.CLINICAL_STAGE/fda_inserts/
    AUTO_COMPRESS = FALSE
    OVERWRITE     = TRUE;

-- ─────────────────────────────────────────────────────────────────────────────
-- STEP 3 – Verify staged files
-- ─────────────────────────────────────────────────────────────────────────────
-- Refresh directory table to pick up newly PUT files
ALTER STAGE RAW.CLINICAL_STAGE REFRESH;

-- List all staged files
LIST @RAW.CLINICAL_STAGE;

-- Expected output: 8 files
--   clinical_notes/hero1_note_ROBERT_CALLAHAN.txt
--   clinical_notes/hero2_note_LINDA_MORENO.txt
--   clinical_notes/hero3_note_JAMES_WHITFIELD_inpatient.txt
--   clinical_notes/hero3_note_JAMES_WHITFIELD_outpatient.txt
--   clinical_notes/hero3_note_JAMES_WHITFIELD_ED.txt
--   fda_inserts/fda_insert_METFORMIN.txt
--   fda_inserts/fda_insert_HBA1C_MONITORING_STANDARD.txt
--   fda_inserts/fda_insert_POLYPHARMACY_HIGH_RISK.txt

-- ─────────────────────────────────────────────────────────────────────────────
-- STEP 4 – PUT STRUCTURED CSV FILES into @RAW.CLINICAL_STAGE/data/
-- ─────────────────────────────────────────────────────────────────────────────
-- CSVs are generated by data_generator/generate_synthetic_data.py
-- Replace <LOCAL_DATA_PATH> with the path to data_generator/output/

PUT file://<LOCAL_DATA_PATH>/output/patients.csv
    @RAW.CLINICAL_STAGE/data/
    AUTO_COMPRESS = FALSE
    OVERWRITE     = TRUE;

PUT file://<LOCAL_DATA_PATH>/output/encounters.csv
    @RAW.CLINICAL_STAGE/data/
    AUTO_COMPRESS = FALSE
    OVERWRITE     = TRUE;

PUT file://<LOCAL_DATA_PATH>/output/claims.csv
    @RAW.CLINICAL_STAGE/data/
    AUTO_COMPRESS = FALSE
    OVERWRITE     = TRUE;

PUT file://<LOCAL_DATA_PATH>/output/labs.csv
    @RAW.CLINICAL_STAGE/data/
    AUTO_COMPRESS = FALSE
    OVERWRITE     = TRUE;

-- ─────────────────────────────────────────────────────────────────────────────
-- STEP 5 – COPY INTO RAW TABLES from staged CSVs
-- ─────────────────────────────────────────────────────────────────────────────
-- Load order respects FK dependency: PATIENTS first, then child tables.

-- 5a. Load PATIENTS (no FK dependencies)
COPY INTO RAW.PATIENTS (
    PATIENT_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, AGE,
    GENDER, RACE, ETHNICITY, ADDRESS_LINE1, CITY, STATE,
    ZIP_CODE, PHONE, EMAIL, INSURANCE_ID, INSURANCE_PLAN,
    PRIMARY_CARE_NPI, ACTIVE_FLAG, CREATED_AT, UPDATED_AT
)
FROM @RAW.CLINICAL_STAGE/data/patients.csv
FILE_FORMAT = (FORMAT_NAME = RAW.CLINICAL_CSV_FORMAT)
ON_ERROR    = 'ABORT_STATEMENT'
PURGE       = FALSE;

-- 5b. Load ENCOUNTERS (FK: PATIENT_ID → PATIENTS)
COPY INTO RAW.ENCOUNTERS (
    ENCOUNTER_ID, PATIENT_ID, ENCOUNTER_DATE, ENCOUNTER_TYPE,
    FACILITY_NAME, FACILITY_NPI, ATTENDING_NPI, PRIMARY_DX_CODE,
    PRIMARY_DX_DESC, SECONDARY_DX_CODES, PROCEDURE_CODES,
    PRESCRIPTION_LIST, DISCHARGE_DATE, DISCHARGE_STATUS,
    NOTES_REF, CREATED_AT, UPDATED_AT
)
FROM @RAW.CLINICAL_STAGE/data/encounters.csv
FILE_FORMAT = (FORMAT_NAME = RAW.CLINICAL_CSV_FORMAT)
ON_ERROR    = 'ABORT_STATEMENT'
PURGE       = FALSE;

-- 5c. Load CLAIMS (FK: PATIENT_ID → PATIENTS, ENCOUNTER_ID → ENCOUNTERS)
COPY INTO RAW.CLAIMS (
    CLAIM_ID, PATIENT_ID, ENCOUNTER_ID, CLAIM_TYPE, CLAIM_DATE,
    SERVICE_FROM_DATE, SERVICE_TO_DATE, BILLED_AMOUNT,
    ALLOWED_AMOUNT, PAID_AMOUNT, PATIENT_COPAY, CLAIM_STATUS,
    DENIAL_REASON, DX_CODE_PRIMARY, DX_CODE_SECONDARY,
    PROCEDURE_CODE, PROCEDURE_DESC, NDC_CODE, DRUG_NAME,
    PROVIDER_NPI, PAYER_ID, PAYER_NAME, CREATED_AT, UPDATED_AT
)
FROM @RAW.CLINICAL_STAGE/data/claims.csv
FILE_FORMAT = (FORMAT_NAME = RAW.CLINICAL_CSV_FORMAT)
ON_ERROR    = 'ABORT_STATEMENT'
PURGE       = FALSE;

-- 5d. Load LABS (FK: PATIENT_ID → PATIENTS, ENCOUNTER_ID → ENCOUNTERS)
COPY INTO RAW.LABS (
    LAB_ID, PATIENT_ID, ENCOUNTER_ID, ORDER_DATE, RESULT_DATE,
    LAB_TEST_CODE, LAB_TEST_NAME, RESULT_VALUE, RESULT_UNIT,
    REFERENCE_RANGE, ABNORMAL_FLAG, RESULT_STATUS,
    PERFORMING_LAB, ORDERING_NPI, CREATED_AT, UPDATED_AT
)
FROM @RAW.CLINICAL_STAGE/data/labs.csv
FILE_FORMAT = (FORMAT_NAME = RAW.CLINICAL_CSV_FORMAT)
ON_ERROR    = 'ABORT_STATEMENT'
PURGE       = FALSE;

-- ─────────────────────────────────────────────────────────────────────────────
-- STEP 6 – Validation queries
-- ─────────────────────────────────────────────────────────────────────────────

-- Row counts
SELECT 'PATIENTS'  AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM RAW.PATIENTS  UNION ALL
SELECT 'ENCOUNTERS',               COUNT(*)              FROM RAW.ENCOUNTERS UNION ALL
SELECT 'CLAIMS',                   COUNT(*)              FROM RAW.CLAIMS     UNION ALL
SELECT 'LABS',                     COUNT(*)              FROM RAW.LABS;

-- Hero 1 – Safety Violation: confirm Metformin Rx + CKD diagnosis
SELECT p.PATIENT_ID, p.FIRST_NAME, p.LAST_NAME, p.AGE,
       e.PRIMARY_DX_CODE, e.PRIMARY_DX_DESC,
       e.PRESCRIPTION_LIST
FROM   RAW.PATIENTS p
JOIN   RAW.ENCOUNTERS e ON p.PATIENT_ID = e.PATIENT_ID
WHERE  p.PATIENT_ID LIKE 'HERO-PT-001%'
ORDER  BY e.ENCOUNTER_DATE;

-- Hero 2 – Care Gap: confirm last HbA1c > 12 months ago
SELECT p.PATIENT_ID, p.FIRST_NAME, p.LAST_NAME, p.AGE,
       l.LAB_TEST_NAME, l.RESULT_VALUE, l.RESULT_DATE,
       DATEDIFF('day', l.RESULT_DATE, CURRENT_DATE()) AS DAYS_SINCE_HBAC1
FROM   RAW.PATIENTS p
JOIN   RAW.LABS     l ON p.PATIENT_ID = l.PATIENT_ID
WHERE  p.PATIENT_ID LIKE 'HERO-PT-002%'
  AND  l.LAB_TEST_CODE = '4548-4'
ORDER  BY l.RESULT_DATE DESC;

-- Hero 3 – High Risk: confirm total claims > $50,000
SELECT p.PATIENT_ID, p.FIRST_NAME, p.LAST_NAME, p.AGE,
       COUNT(c.CLAIM_ID)           AS TOTAL_CLAIMS,
       SUM(c.BILLED_AMOUNT)        AS TOTAL_BILLED,
       SUM(c.PAID_AMOUNT)          AS TOTAL_PAID
FROM   RAW.PATIENTS p
JOIN   RAW.CLAIMS   c ON p.PATIENT_ID = c.PATIENT_ID
WHERE  p.PATIENT_ID LIKE 'HERO-PT-003%'
GROUP  BY 1, 2, 3, 4;

-- Referential integrity spot-check (should return 0 orphans)
SELECT 'Orphan encounters' AS CHECK_TYPE,
       COUNT(*)            AS ORPHAN_COUNT
FROM   RAW.ENCOUNTERS e
WHERE  NOT EXISTS (
    SELECT 1 FROM RAW.PATIENTS p WHERE p.PATIENT_ID = e.PATIENT_ID
)
UNION ALL
SELECT 'Orphan claims',
       COUNT(*)
FROM   RAW.CLAIMS c
WHERE  NOT EXISTS (
    SELECT 1 FROM RAW.PATIENTS p WHERE p.PATIENT_ID = c.PATIENT_ID
)
UNION ALL
SELECT 'Orphan labs',
       COUNT(*)
FROM   RAW.LABS l
WHERE  NOT EXISTS (
    SELECT 1 FROM RAW.PATIENTS p WHERE p.PATIENT_ID = l.PATIENT_ID
);
